# Generated by Django 3.2.16 on 2022-10-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('sur_name', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('facebook', models.CharField(blank=True, max_length=20, null=True)),
                ('twitter', models.CharField(blank=True, max_length=20, null=True)),
                ('instagram', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=10)),
                ('cv', models.FileField(upload_to=None)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
