# Generated by Django 3.2.16 on 2022-12-13 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helsings_school.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('username', models.CharField(blank=True, max_length=30, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=10)),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='firstname')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='lastname')),
                ('second_name', models.CharField(max_length=20)),
                ('dob', models.DateField(null=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('facebook', models.CharField(blank=True, max_length=20, null=True)),
                ('twitter', models.CharField(blank=True, max_length=20, null=True)),
                ('instagram', models.CharField(blank=True, max_length=20, null=True)),
                ('cv', models.FileField(upload_to=None)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=True, verbose_name='staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
            managers=[
                ('objects', helsings_school.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Alumnus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled', models.CharField(max_length=10)),
                ('graduated', models.CharField(max_length=10)),
                ('headmaster', models.CharField(max_length=15)),
                ('famous', models.CharField(max_length=15)),
                ('results', models.CharField(max_length=10)),
                ('occupation', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=15)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'alumnus',
                'verbose_name_plural': 'alumni',
            },
        ),
    ]
