# Generated by Django 3.2.16 on 2022-10-18 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helsings_school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reg_users',
            old_name='sur_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='reg_users',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='reg_users',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
