# Generated by Django 3.2.16 on 2022-10-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helsings_school', '0002_auto_20221018_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_users',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
