# Generated by Django 3.2.16 on 2022-10-19 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('helsings_school', '0003_alter_reg_users_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=20)),
                ('second_name', models.CharField(max_length=20)),
                ('dob', models.DateField(null=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('facebook', models.CharField(blank=True, max_length=20, null=True)),
                ('twitter', models.CharField(blank=True, max_length=20, null=True)),
                ('instagram', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=10)),
                ('cv', models.FileField(upload_to=None)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Reg_users',
        ),
    ]
