# Generated by Django 3.2.16 on 2022-12-15 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helsings_school', '0004_alter_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='admin'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff'),
        ),
    ]
