# Generated by Django 3.2.16 on 2022-10-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helsings_school', '0004_auto_20221019_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='registered',
            name='user_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
