# Generated by Django 3.2.16 on 2022-12-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helsings_school', '0005_auto_20221215_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='staff'),
        ),
    ]
