# Generated by Django 3.2.16 on 2022-12-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helsings_school', '0007_alter_alumnus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reg_no',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
