# Generated by Django 3.2.16 on 2022-10-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helsings_school', '0007_alter_registered_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registered',
            old_name='user_name',
            new_name='username',
        ),
    ]
