# Generated by Django 3.2.16 on 2022-12-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helsings_school', '0008_profile_reg_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reg_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
