# Generated by Django 3.2.16 on 2022-10-19 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helsings_school', '0009_registered_is_superuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='registered',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='registered',
            name='last_login',
        ),
        migrations.AddField(
            model_name='registered',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registered',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registered',
            name='user',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
