# Generated by Django 3.2.16 on 2022-10-19 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helsings_school', '0010_auto_20221019_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registered',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registered',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='registered',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='registered',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='registered',
            name='is_authenticated',
        ),
        migrations.RemoveField(
            model_name='registered',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='registered',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='registered',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='registered',
            name='password',
        ),
        migrations.RemoveField(
            model_name='registered',
            name='username',
        ),
    ]
