# Generated by Django 3.2.16 on 2022-10-21 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helsings_school', '0012_alter_registered_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registered',
            name='id',
        ),
        migrations.AlterField(
            model_name='registered',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
