# Generated by Django 3.2.16 on 2022-10-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helsings_school', '0014_auto_20221021_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('enrolled', models.CharField(max_length=4)),
                ('graduated', models.CharField(max_length=4)),
                ('headmaster', models.CharField(max_length=15)),
                ('famous', models.CharField(max_length=15)),
                ('results', models.CharField(max_length=10)),
                ('occupation', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=15)),
            ],
        ),
    ]
